import math
H_OR = H_OD / 2
S_IR = S_ID / 2
S_OR = S_IR + S_THK
S_LEN = S_H + T_LEN
plane = Plane.PlaneZX
result = DatumPlaneCreator.Create(plane, False, None)
plane = Plane.PlaneXY
result = DatumPlaneCreator.Create(plane, False, None)
plane = Plane.PlaneYZ
result = DatumPlaneCreator.Create(plane, False, None)
sectionPlane = Plane.PlaneXY
result = ViewHelper.SetSketchPlane(sectionPlane, None)
point1 = Point2D.Create(MM(0), MM(0))
point2 = Point2D.Create(MM(H_OR), MM(0))
point3 = Point2D.Create(MM(H_OR), MM(H_THK))
result = SketchRectangle.Create(point1, point2, point3)
start = Point2D.Create(MM(S_IR), MM(0))
end = Point2D.Create(MM(S_IR), MM(-T_LEN))
result = SketchLine.Create(start, end)
start = Point2D.Create(MM(S_IR), MM(-T_LEN))
end = Point2D.Create(MM(S_IR), MM(-S_LEN))
result = SketchLine.Create(start, end)
start = Point2D.Create(MM(S_IR), MM(-S_LEN))
end = Point2D.Create(MM(S_OR), MM(-S_LEN))
result = SketchLine.Create(start, end)
start = Point2D.Create(MM(S_OR), MM(-T_LEN))
end = Point2D.Create(MM(S_OR), MM(-S_LEN))
result = SketchLine.Create(start, end)
start = Point2D.Create(MM(S_OR), MM(-T_LEN))
end = Point2D.Create(MM(H_OR), MM(0))
result = SketchLine.Create(start, end)
start = Point2D.Create(MM(S_IR), MM(-T_LEN))
end = Point2D.Create(MM(S_OR), MM(-T_LEN))
result = SketchLine.Create(start, end)
mode = InteractionMode.Solid
result = ViewHelper.SetViewMode(mode, None)
for i in range(0, 3, 1):
    selection =Selection.Create(GetRootPart().Bodies[0].Faces[0])
    axis=Line.Create(Point.Origin, Direction.DirY)
    options = RevolveFaceOptions()
    options.ExtrudeType = ExtrudeType.ForceIndependent
    result = RevolveFaces.Execute(selection, axis, DEG(360), options)