plane = Plane.PlaneZX
result = DatumPlaneCreator.Create(plane, False, None)
plane = Plane.PlaneXY
result = DatumPlaneCreator.Create(plane, False, None)
plane = Plane.PlaneYZ
result = DatumPlaneCreator.Create(plane, False, None)
sectionPlane = Plane.PlaneXY
result = ViewHelper.SetSketchPlane(sectionPlane, None)
S_OR = S_OD / 2
point1 = Point2D.Create(MM(S_OR - S_THK), MM(0))
point2 = Point2D.Create(MM(S_OR), MM(0))
point3 = Point2D.Create(MM(S_OR), MM(S_H))
result = SketchRectangle.Create(point1, point2, point3)
mode = InteractionMode.Solid
result = ViewHelper.SetViewMode(mode, None)
selection = Selection.Create(GetRootPart().Bodies[0].Faces[0])
axis=Line.Create(Point.Origin, Direction.DirY)
options = RevolveFaceOptions()
options.ExtrudeType = ExtrudeType.Add
result = RevolveFaces.Execute(selection, axis, DEG(360), options)