"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

export const LANGUAGES = [
  { code: "en", name: "English", flag: "🇺🇸" },
  { code: "fr", name: "Français", flag: "🇫🇷" },
  { code: "de", name: "Deutsch", flag: "🇩🇪" },
  { code: "it", name: "Italiano", flag: "🇮🇹" },
  { code: "es", name: "Español", flag: "🇪🇸" },
  { code: "nl", name: "Nederlands", flag: "🇳🇱" },
  { code: "pl", name: "Polski", flag: "🇵🇱" },
  { code: "pt", name: "Português", flag: "🇧🇷" },
  { code: "cs", name: "Čeština", flag: "🇨🇿" },
  { code: "ro", name: "Română", flag: "🇷🇴" },
  { code: "sv", name: "Svenska", flag: "🇸🇪" },
  { code: "hu", name: "Magyar", flag: "🇭🇺" },
  { code: "tr", name: "Türkçe", flag: "🇹🇷" },
  { code: "el", name: "Ελληνικά", flag: "🇬🇷" },
  { code: "uk", name: "Українська", flag: "🇺🇦" },
  { code: "ru", name: "Русский", flag: "🇷🇺" },
  { code: "sw", name: "Kiswahili", flag: "🇰🇪" },
  { code: "vi", name: "Tiếng Việt", flag: "🇻🇳" },
  { code: "zh-CN", name: "简体中文", flag: "🇨🇳" },
  { code: "zh-TW", name: "繁體中文", flag: "🇹🇼" },
  { code: "ja", name: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "한국어", flag: "🇰🇷" },
  { code: "th", name: "ไทย", flag: "🇹🇭" },
  { code: "bn", name: "বাংলা", flag: "🇧🇩" },
  { code: "hi", name: "हिन्दी", flag: "🇮🇳" },
  { code: "mn", name: "Монгол", flag: "🇲🇳" },
]

export type LangCode = typeof LANGUAGES[number]["code"]

export type Translations = typeof EN

const EN = {
  appName: "SpaceGeo AI",
  newChat: "New Chat",
  backgroundTasks: "Background tasks",
  generalKnowledges: "General knowledges",
  myAutomations: "My automations",
  publicAutomations: "Public automations",
  cadAgentChats: "CAD Agent Chats",
  noChatsYet: "No chats yet",
  noTasksYet: "No tasks yet",
  settings: "Settings",
  general: "General",
  account: "Account",
  generalSettings: "General Settings",
  language: "Language",
  theme: "Theme",
  darkMode: "Dark Mode",
  lightMode: "Light Mode",
  cadSoftware: "CAD Software",
  agentExecution: "Agent execution in",
  agentDesc: "What the agent may do to your open documents during a turn. Read only keeps inspection and blocks edits with safety checks, but it is not a sandbox.",
  execReadOnly: "Read only: inspect documents, never edit them",
  execAskFirst: "Ask first: approve each execution in a dialog (recommended)",
  execAlwaysAllow: "Always allow: execute without asking",
  connectionMethod: "Connection Method",
  accountSettings: "Account Settings",
  name: "Name",
  email: "Email",
  weeklyUsage: "Weekly usage",
  planUsageLimit: "Plan usage limit",
  resetsOn: "Resets on",
  agentRuns: "Agent runs, background tasks and completed drawing tasks share your weekly allowance.",
  logout: "Logout",
  dashboard: "Dashboard",
  whatBuild: "What would you like to build?",
  describeModel: "Describe your part, its dimensions, and the details that matter. We'll build it together in",
  askAnything: "Ask about",
  orDescribe: "or describe a model to create…",
  listening: "Listening…",
  online: "Connected",
  offline: "is not running. Start",
  offlineEnd: ", open your document, then connect again.",
  checking: "Checking",
  searchChats: "Search chats…",
  version: "Version 2.0.1 · SpaceGeo AI",
  retry: "Retry",
  somethingWrong: "Something went wrong",
  stop: "Stop",
  send: "Send",
  selectModel: "Select AI model",
  attachImage: "Attach image",
  voiceInput: "Voice input",
  stopRecording: "Stop recording",
  toggleSidebar: "Toggle sidebar",
  refreshConnection: "Refresh Connection",
  toggleDarkMode: "Toggle dark mode",
  viewUsage: "View plan usage",
  deleteChat: "Delete",
  selectCAD: "Select CAD Software",
}

const TRANSLATIONS: Record<string, Partial<Translations>> = {
  fr: {
    appName: "SpaceGeo AI",
    newChat: "Nouvelle conversation",
    backgroundTasks: "Tâches en arrière-plan",
    generalKnowledges: "Connaissances générales",
    myAutomations: "Mes automatisations",
    publicAutomations: "Automatisations publiques",
    cadAgentChats: "Chats Agent CAO",
    noChatsYet: "Aucune conversation",
    noTasksYet: "Aucune tâche",
    settings: "Paramètres",
    general: "Général",
    account: "Compte",
    generalSettings: "Paramètres généraux",
    language: "Langue",
    theme: "Thème",
    darkMode: "Mode sombre",
    lightMode: "Mode clair",
    cadSoftware: "Logiciel CAO",
    agentExecution: "Exécution de l'agent dans",
    execReadOnly: "Lecture seule : inspecter les documents, jamais les modifier",
    execAskFirst: "Demander d'abord : approuver chaque exécution dans un dialogue (recommandé)",
    execAlwaysAllow: "Toujours autoriser : exécuter sans demander",
    connectionMethod: "Méthode de connexion",
    accountSettings: "Paramètres du compte",
    name: "Nom",
    email: "E-mail",
    weeklyUsage: "Utilisation hebdomadaire",
    planUsageLimit: "Limite d'utilisation du plan",
    resetsOn: "Réinitialise le",
    logout: "Déconnexion",
    dashboard: "Tableau de bord",
    whatBuild: "Que souhaitez-vous construire ?",
    describeModel: "Décrivez votre pièce, ses dimensions et les détails importants. Nous la construirons ensemble dans",
    listening: "Écoute…",
    online: "Connecté",
    retry: "Réessayer",
    somethingWrong: "Une erreur s'est produite",
  },
  de: {
    newChat: "Neuer Chat",
    backgroundTasks: "Hintergrundaufgaben",
    generalKnowledges: "Allgemeinwissen",
    myAutomations: "Meine Automatisierungen",
    publicAutomations: "Öffentliche Automatisierungen",
    cadAgentChats: "CAD-Agent-Chats",
    noChatsYet: "Noch keine Chats",
    settings: "Einstellungen",
    general: "Allgemein",
    account: "Konto",
    generalSettings: "Allgemeine Einstellungen",
    language: "Sprache",
    theme: "Thema",
    darkMode: "Dunkelmodus",
    lightMode: "Hellmodus",
    cadSoftware: "CAD-Software",
    agentExecution: "Agentenausführung in",
    execReadOnly: "Nur lesen: Dokumente prüfen, nie bearbeiten",
    execAskFirst: "Zuerst fragen: jede Ausführung in einem Dialog bestätigen (empfohlen)",
    execAlwaysAllow: "Immer erlauben: ohne Nachfrage ausführen",
    connectionMethod: "Verbindungsmethode",
    accountSettings: "Kontoeinstellungen",
    name: "Name",
    email: "E-Mail",
    weeklyUsage: "Wöchentliche Nutzung",
    logout: "Abmelden",
    dashboard: "Dashboard",
    whatBuild: "Was möchten Sie erstellen?",
    describeModel: "Beschreiben Sie Ihr Teil, seine Abmessungen und wichtige Details. Wir bauen es gemeinsam in",
    listening: "Höre zu…",
    retry: "Wiederholen",
    somethingWrong: "Etwas ist schiefgelaufen",
  },
  es: {
    newChat: "Nuevo chat",
    backgroundTasks: "Tareas en segundo plano",
    generalKnowledges: "Conocimientos generales",
    myAutomations: "Mis automatizaciones",
    publicAutomations: "Automatizaciones públicas",
    cadAgentChats: "Chats del agente CAD",
    settings: "Configuración",
    general: "General",
    account: "Cuenta",
    language: "Idioma",
    theme: "Tema",
    darkMode: "Modo oscuro",
    lightMode: "Modo claro",
    cadSoftware: "Software CAD",
    agentExecution: "Ejecución del agente en",
    execReadOnly: "Solo lectura: inspeccionar documentos, nunca editarlos",
    execAskFirst: "Preguntar primero: aprobar cada ejecución en un diálogo (recomendado)",
    execAlwaysAllow: "Permitir siempre: ejecutar sin preguntar",
    logout: "Cerrar sesión",
    dashboard: "Panel de control",
    whatBuild: "¿Qué deseas crear?",
    describeModel: "Describe tu pieza, sus dimensiones y los detalles importantes. Lo construiremos juntos en",
    listening: "Escuchando…",
    retry: "Reintentar",
    somethingWrong: "Algo salió mal",
  },
  it: {
    newChat: "Nuova chat",
    backgroundTasks: "Attività in background",
    generalKnowledges: "Conoscenze generali",
    myAutomations: "Le mie automazioni",
    publicAutomations: "Automazioni pubbliche",
    settings: "Impostazioni",
    general: "Generale",
    account: "Account",
    language: "Lingua",
    theme: "Tema",
    darkMode: "Modalità scura",
    lightMode: "Modalità chiara",
    cadSoftware: "Software CAD",
    logout: "Disconnetti",
    dashboard: "Dashboard",
    whatBuild: "Cosa vorresti costruire?",
    describeModel: "Descrivi il tuo pezzo, le sue dimensioni e i dettagli importanti. Lo costruiremo insieme in",
    listening: "Ascolto…",
    retry: "Riprova",
    somethingWrong: "Qualcosa è andato storto",
  },
  zh_CN: {
    newChat: "新对话",
    backgroundTasks: "后台任务",
    generalKnowledges: "通用知识",
    myAutomations: "我的自动化",
    publicAutomations: "公共自动化",
    cadAgentChats: "CAD 代理对话",
    settings: "设置",
    general: "常规",
    account: "账户",
    language: "语言",
    theme: "主题",
    darkMode: "深色模式",
    lightMode: "浅色模式",
    cadSoftware: "CAD 软件",
    logout: "退出登录",
    dashboard: "仪表板",
    whatBuild: "您想构建什么？",
    describeModel: "描述您的零件、尺寸和重要细节。我们将在以下软件中共同构建",
    listening: "正在聆听…",
    retry: "重试",
    somethingWrong: "出了点问题",
  },
  ja: {
    newChat: "新しいチャット",
    backgroundTasks: "バックグラウンドタスク",
    generalKnowledges: "一般知識",
    myAutomations: "マイオートメーション",
    publicAutomations: "公開オートメーション",
    settings: "設定",
    general: "一般",
    account: "アカウント",
    language: "言語",
    theme: "テーマ",
    darkMode: "ダークモード",
    lightMode: "ライトモード",
    cadSoftware: "CADソフトウェア",
    logout: "ログアウト",
    dashboard: "ダッシュボード",
    whatBuild: "何を作りたいですか？",
    describeModel: "部品、寸法、重要な詳細を説明してください。一緒に作りましょう",
    listening: "聞いています…",
    retry: "再試行",
    somethingWrong: "エラーが発生しました",
  },
  ko: {
    newChat: "새 채팅",
    backgroundTasks: "백그라운드 작업",
    settings: "설정",
    general: "일반",
    account: "계정",
    language: "언어",
    theme: "테마",
    darkMode: "다크 모드",
    lightMode: "라이트 모드",
    cadSoftware: "CAD 소프트웨어",
    logout: "로그아웃",
    dashboard: "대시보드",
    whatBuild: "무엇을 만들고 싶으신가요?",
    describeModel: "부품, 치수 및 중요한 세부 사항을 설명하세요. 함께 만들겠습니다",
    listening: "듣는 중…",
    retry: "다시 시도",
    somethingWrong: "오류가 발생했습니다",
  },
  hi: {
    newChat: "नई चैट",
    backgroundTasks: "पृष्ठभूमि कार्य",
    settings: "सेटिंग्स",
    general: "सामान्य",
    account: "खाता",
    language: "भाषा",
    theme: "थीम",
    darkMode: "डार्क मोड",
    lightMode: "लाइट मोड",
    cadSoftware: "CAD सॉफ्टवेयर",
    logout: "लॉग आउट",
    dashboard: "डैशबोर्ड",
    whatBuild: "आप क्या बनाना चाहते हैं?",
    describeModel: "अपने भाग, आयाम और महत्वपूर्ण विवरण बताएं। हम इसे एक साथ बनाएंगे",
    listening: "सुन रहे हैं…",
    retry: "पुनः प्रयास करें",
    somethingWrong: "कुछ गलत हुआ",
  },
  ru: {
    newChat: "Новый чат",
    backgroundTasks: "Фоновые задачи",
    settings: "Настройки",
    general: "Основные",
    account: "Аккаунт",
    language: "Язык",
    theme: "Тема",
    darkMode: "Тёмная тема",
    lightMode: "Светлая тема",
    cadSoftware: "CAD-программа",
    logout: "Выйти",
    dashboard: "Панель управления",
    whatBuild: "Что вы хотите создать?",
    describeModel: "Опишите деталь, её размеры и важные подробности. Мы создадим это вместе в",
    listening: "Слушаю…",
    retry: "Повторить",
    somethingWrong: "Что-то пошло не так",
  },
  tr: {
    newChat: "Yeni Sohbet",
    settings: "Ayarlar",
    general: "Genel",
    account: "Hesap",
    language: "Dil",
    theme: "Tema",
    darkMode: "Karanlık Mod",
    lightMode: "Aydınlık Mod",
    cadSoftware: "CAD Yazılımı",
    logout: "Çıkış Yap",
    dashboard: "Pano",
    whatBuild: "Ne inşa etmek istersiniz?",
    listening: "Dinleniyor…",
    retry: "Yeniden Dene",
    somethingWrong: "Bir şeyler ters gitti",
  },
  pt: {
    newChat: "Novo chat",
    settings: "Configurações",
    general: "Geral",
    account: "Conta",
    language: "Idioma",
    theme: "Tema",
    darkMode: "Modo escuro",
    lightMode: "Modo claro",
    cadSoftware: "Software CAD",
    logout: "Sair",
    dashboard: "Painel",
    whatBuild: "O que você gostaria de construir?",
    listening: "Ouvindo…",
    retry: "Tentar novamente",
    somethingWrong: "Algo deu errado",
  },
}

const LANG_CODE_MAP: Record<string, string> = {
  "zh-CN": "zh_CN",
  "zh-TW": "zh_TW",
}

function getTranslations(langCode: string): Translations {
  const key = LANG_CODE_MAP[langCode] || langCode
  const partial = TRANSLATIONS[key] || {}
  return { ...EN, ...partial }
}

interface LangContextType {
  lang: LangCode
  setLang: (lang: LangCode) => void
  t: Translations
  currentLang: typeof LANGUAGES[number]
}

const LangContext = createContext<LangContextType>({
  lang: "en",
  setLang: () => {},
  t: EN,
  currentLang: LANGUAGES[0],
})

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>("en")

  useEffect(() => {
    const stored = localStorage.getItem("sg-language") as LangCode | null
    if (stored) setLangState(stored)
  }, [])

  const setLang = (newLang: LangCode) => {
    setLangState(newLang)
    localStorage.setItem("sg-language", newLang)
    document.documentElement.lang = newLang
  }

  const t = getTranslations(lang)
  const currentLang = LANGUAGES.find((l) => l.code === lang) || LANGUAGES[0]

  return (
    <LangContext.Provider value={{ lang, setLang, t, currentLang }}>
      {children}
    </LangContext.Provider>
  )
}

export function useLang() {
  return useContext(LangContext)
}
